package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallCollect;
import org.mochou.mymall.db.domain.MymallCollectExample;

public interface MymallCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     */
    long countByExample(MymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     */
    int deleteByExample(MymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     */
    int insert(MymallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     */
    int insertSelective(MymallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallCollect selectOneByExample(MymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallCollect selectOneByExampleSelective(@Param("example") MymallCollectExample example, @Param("selective") MymallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallCollect> selectByExampleSelective(@Param("example") MymallCollectExample example, @Param("selective") MymallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     */
    List<MymallCollect> selectByExample(MymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     */
    MymallCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallCollect record, @Param("example") MymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallCollect record, @Param("example") MymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MymallCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_collect
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}