package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallTopic;
import org.mochou.mymall.db.domain.MymallTopicExample;

public interface MymallTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    long countByExample(MymallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    int deleteByExample(MymallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    int insert(MymallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    int insertSelective(MymallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallTopic selectOneByExample(MymallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallTopic selectOneByExampleSelective(@Param("example") MymallTopicExample example, @Param("selective") MymallTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallTopic selectOneByExampleWithBLOBs(MymallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallTopic> selectByExampleSelective(@Param("example") MymallTopicExample example, @Param("selective") MymallTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    List<MymallTopic> selectByExampleWithBLOBs(MymallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    List<MymallTopic> selectByExample(MymallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    MymallTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallTopic record, @Param("example") MymallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") MymallTopic record, @Param("example") MymallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallTopic record, @Param("example") MymallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MymallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MymallTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}