package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallComment;
import org.mochou.mymall.db.domain.MymallCommentExample;

public interface MymallCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     */
    long countByExample(MymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     */
    int deleteByExample(MymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     */
    int insert(MymallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     */
    int insertSelective(MymallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallComment selectOneByExample(MymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallComment selectOneByExampleSelective(@Param("example") MymallCommentExample example, @Param("selective") MymallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallComment> selectByExampleSelective(@Param("example") MymallCommentExample example, @Param("selective") MymallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     */
    List<MymallComment> selectByExample(MymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallComment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     */
    MymallComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallComment record, @Param("example") MymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallComment record, @Param("example") MymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MymallCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}