package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallUserFormid;
import org.mochou.mymall.db.domain.MymallUserFormidExample;

public interface MymallUserFormidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     */
    long countByExample(MymallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     */
    int deleteByExample(MymallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     */
    int insert(MymallUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     */
    int insertSelective(MymallUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallUserFormid selectOneByExample(MymallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallUserFormid selectOneByExampleSelective(@Param("example") MymallUserFormidExample example, @Param("selective") MymallUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallUserFormid> selectByExampleSelective(@Param("example") MymallUserFormidExample example, @Param("selective") MymallUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     */
    List<MymallUserFormid> selectByExample(MymallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallUserFormid selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     */
    MymallUserFormid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallUserFormid selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallUserFormid record, @Param("example") MymallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallUserFormid record, @Param("example") MymallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MymallUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}