package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallRegion;
import org.mochou.mymall.db.domain.MymallRegionExample;

public interface MymallRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     */
    long countByExample(MymallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     */
    int deleteByExample(MymallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     */
    int insert(MymallRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     */
    int insertSelective(MymallRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallRegion selectOneByExample(MymallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallRegion selectOneByExampleSelective(@Param("example") MymallRegionExample example, @Param("selective") MymallRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallRegion> selectByExampleSelective(@Param("example") MymallRegionExample example, @Param("selective") MymallRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     */
    List<MymallRegion> selectByExample(MymallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     */
    MymallRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallRegion record, @Param("example") MymallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallRegion record, @Param("example") MymallRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallRegion record);
}