package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallGroupon;
import org.mochou.mymall.db.domain.MymallGrouponExample;

public interface MymallGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     */
    long countByExample(MymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(MymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     */
    int insert(MymallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     */
    int insertSelective(MymallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallGroupon selectOneByExample(MymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallGroupon selectOneByExampleSelective(@Param("example") MymallGrouponExample example, @Param("selective") MymallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallGroupon> selectByExampleSelective(@Param("example") MymallGrouponExample example, @Param("selective") MymallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     */
    List<MymallGroupon> selectByExample(MymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallGroupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallGroupon.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     */
    MymallGroupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallGroupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallGroupon record, @Param("example") MymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallGroupon record, @Param("example") MymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MymallGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}