package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallGoods;
import org.mochou.mymall.db.domain.MymallGoodsExample;

public interface MymallGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    long countByExample(MymallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    int deleteByExample(MymallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    int insert(MymallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    int insertSelective(MymallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallGoods selectOneByExample(MymallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallGoods selectOneByExampleSelective(@Param("example") MymallGoodsExample example, @Param("selective") MymallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallGoods selectOneByExampleWithBLOBs(MymallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallGoods> selectByExampleSelective(@Param("example") MymallGoodsExample example, @Param("selective") MymallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    List<MymallGoods> selectByExampleWithBLOBs(MymallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    List<MymallGoods> selectByExample(MymallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    MymallGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallGoods record, @Param("example") MymallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") MymallGoods record, @Param("example") MymallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallGoods record, @Param("example") MymallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MymallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MymallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}