package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallFootprint;
import org.mochou.mymall.db.domain.MymallFootprintExample;

public interface MymallFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     */
    long countByExample(MymallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(MymallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     */
    int insert(MymallFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     */
    int insertSelective(MymallFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallFootprint selectOneByExample(MymallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallFootprint selectOneByExampleSelective(@Param("example") MymallFootprintExample example, @Param("selective") MymallFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallFootprint> selectByExampleSelective(@Param("example") MymallFootprintExample example, @Param("selective") MymallFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     */
    List<MymallFootprint> selectByExample(MymallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     */
    MymallFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallFootprint record, @Param("example") MymallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallFootprint record, @Param("example") MymallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MymallFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}