package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallSystem;
import org.mochou.mymall.db.domain.MymallSystemExample;

public interface MymallSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     */
    long countByExample(MymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     */
    int deleteByExample(MymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     */
    int insert(MymallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     */
    int insertSelective(MymallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallSystem selectOneByExample(MymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallSystem selectOneByExampleSelective(@Param("example") MymallSystemExample example, @Param("selective") MymallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallSystem> selectByExampleSelective(@Param("example") MymallSystemExample example, @Param("selective") MymallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     */
    List<MymallSystem> selectByExample(MymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     */
    MymallSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallSystem record, @Param("example") MymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallSystem record, @Param("example") MymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MymallSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_system
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}