package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallCategory;
import org.mochou.mymall.db.domain.MymallCategoryExample;

public interface MymallCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     */
    long countByExample(MymallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     */
    int deleteByExample(MymallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     */
    int insert(MymallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     */
    int insertSelective(MymallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallCategory selectOneByExample(MymallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallCategory selectOneByExampleSelective(@Param("example") MymallCategoryExample example, @Param("selective") MymallCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallCategory> selectByExampleSelective(@Param("example") MymallCategoryExample example, @Param("selective") MymallCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     */
    List<MymallCategory> selectByExample(MymallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     */
    MymallCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallCategory record, @Param("example") MymallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallCategory record, @Param("example") MymallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MymallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}