package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallGrouponRules;
import org.mochou.mymall.db.domain.MymallGrouponRulesExample;

public interface MymallGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(MymallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(MymallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     */
    int insert(MymallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(MymallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallGrouponRules selectOneByExample(MymallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallGrouponRules selectOneByExampleSelective(@Param("example") MymallGrouponRulesExample example, @Param("selective") MymallGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallGrouponRules> selectByExampleSelective(@Param("example") MymallGrouponRulesExample example, @Param("selective") MymallGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     */
    List<MymallGrouponRules> selectByExample(MymallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallGrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     */
    MymallGrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallGrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallGrouponRules record, @Param("example") MymallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallGrouponRules record, @Param("example") MymallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MymallGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}