package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallStorage;
import org.mochou.mymall.db.domain.MymallStorageExample;

public interface MymallStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     */
    long countByExample(MymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     */
    int deleteByExample(MymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     */
    int insert(MymallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     */
    int insertSelective(MymallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallStorage selectOneByExample(MymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallStorage selectOneByExampleSelective(@Param("example") MymallStorageExample example, @Param("selective") MymallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallStorage> selectByExampleSelective(@Param("example") MymallStorageExample example, @Param("selective") MymallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     */
    List<MymallStorage> selectByExample(MymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     */
    MymallStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallStorage record, @Param("example") MymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallStorage record, @Param("example") MymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MymallStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}