package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallCart;
import org.mochou.mymall.db.domain.MymallCartExample;

public interface MymallCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     */
    long countByExample(MymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     */
    int deleteByExample(MymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     */
    int insert(MymallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     */
    int insertSelective(MymallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallCart selectOneByExample(MymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallCart selectOneByExampleSelective(@Param("example") MymallCartExample example, @Param("selective") MymallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallCart> selectByExampleSelective(@Param("example") MymallCartExample example, @Param("selective") MymallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     */
    List<MymallCart> selectByExample(MymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     */
    MymallCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallCart record, @Param("example") MymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallCart record, @Param("example") MymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MymallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}