package org.mochou.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mochou.mymall.db.domain.MymallUser;
import org.mochou.mymall.db.domain.MymallUserExample;

public interface MymallUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     */
    long countByExample(MymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     */
    int deleteByExample(MymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     */
    int insert(MymallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     */
    int insertSelective(MymallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallUser selectOneByExample(MymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallUser selectOneByExampleSelective(@Param("example") MymallUserExample example, @Param("selective") MymallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<MymallUser> selectByExampleSelective(@Param("example") MymallUserExample example, @Param("selective") MymallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     */
    List<MymallUser> selectByExample(MymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     */
    MymallUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MymallUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallUser record, @Param("example") MymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallUser record, @Param("example") MymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") MymallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}